// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A summary and comparison of the principal's access under the current
/// (baseline) policies and the proposed (simulated) policies for a single
/// access tuple.
public struct AccessStateDiff: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The results of evaluating the access tuple under the current (baseline)
  /// policies.
  ///
  /// If the [AccessState][google.cloud.policysimulator.v1.AccessState] couldn't
  /// be fully evaluated, this field explains why.
  ///
  /// [google.cloud.policysimulator.v1.AccessState]: <doc:AccessState>
  public var baseline: ExplainedAccess? = nil

  /// The results of evaluating the access tuple under the proposed (simulated)
  /// policies.
  ///
  /// If the AccessState couldn't be fully evaluated, this field explains why.
  public var simulated: ExplainedAccess? = nil

  /// How the principal's access, specified in the AccessState field, changed
  /// between the current (baseline) policies and proposed (simulated) policies.
  public var accessChange: AccessStateDiff.AccessChangeType = AccessStateDiff.AccessChangeType()

  /// Initialize a new instance of `AccessStateDiff`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessStateDiff().with { $0.baseline = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// How the principal's access, specified in the AccessState field, changed
  /// between the current (baseline) policies and proposed (simulated) policies.
  public enum AccessChangeType: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The principal's access did not change.
    /// This includes the case where both baseline and simulated are UNKNOWN,
    /// but the unknown information is equivalent.
    case noChange
    /// The principal's access under both the current policies and the proposed
    /// policies is `UNKNOWN`, but the unknown information differs between them.
    case unknownChange
    /// The principal had access under the current policies (`GRANTED`), but will
    /// no longer have access after the proposed changes (`NOT_GRANTED`).
    case accessRevoked
    /// The principal did not have access under the current policies
    /// (`NOT_GRANTED`), but will have access after the proposed changes
    /// (`GRANTED`).
    case accessGained
    /// This result can occur for the following reasons:
    ///
    /// * The principal had access under the current policies (`GRANTED`), but
    ///   their access after the proposed changes is `UNKNOWN`.
    ///
    /// * The principal's access under the current policies is `UNKNOWN`, but
    /// they
    ///   will not have access after the proposed changes (`NOT_GRANTED`).
    case accessMaybeRevoked
    /// This result can occur for the following reasons:
    ///
    /// * The principal did not have access under the current policies
    ///   (`NOT_GRANTED`), but their access after the proposed changes is
    ///   `UNKNOWN`.
    ///
    /// * The principal's access under the current policies is `UNKNOWN`, but
    /// they will have access after the proposed changes (`GRANTED`).
    case accessMaybeGained
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .noChange: return 1
      case .unknownChange: return 2
      case .accessRevoked: return 3
      case .accessGained: return 4
      case .accessMaybeRevoked: return 5
      case .accessMaybeGained: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ACCESS_CHANGE_TYPE_UNSPECIFIED"
      case .noChange: return "NO_CHANGE"
      case .unknownChange: return "UNKNOWN_CHANGE"
      case .accessRevoked: return "ACCESS_REVOKED"
      case .accessGained: return "ACCESS_GAINED"
      case .accessMaybeRevoked: return "ACCESS_MAYBE_REVOKED"
      case .accessMaybeGained: return "ACCESS_MAYBE_GAINED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AccessChangeType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ACCESS_CHANGE_TYPE_UNSPECIFIED": self = .unspecified
      case "NO_CHANGE": self = .noChange
      case "UNKNOWN_CHANGE": self = .unknownChange
      case "ACCESS_REVOKED": self = .accessRevoked
      case "ACCESS_GAINED": self = .accessGained
      case "ACCESS_MAYBE_REVOKED": self = .accessMaybeRevoked
      case "ACCESS_MAYBE_GAINED": self = .accessMaybeGained
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AccessChangeType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .noChange
      case 2: self = .unknownChange
      case 3: self = .accessRevoked
      case 4: self = .accessGained
      case 5: self = .accessMaybeRevoked
      case 6: self = .accessMaybeGained
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .noChange: return try container.encode(1)
      case .unknownChange: return try container.encode(2)
      case .accessRevoked: return try container.encode(3)
      case .accessGained: return try container.encode(4)
      case .accessMaybeRevoked: return try container.encode(5)
      case .accessMaybeGained: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.AccessStateDiff"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
