// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// CreateOrgPolicyViolationsPreviewOperationMetadata is metadata about an
/// OrgPolicyViolationsPreview generations operation.
public struct CreateOrgPolicyViolationsPreviewOperationMetadata: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Time when the request was received.
  public var requestTime: GoogleCloudWKT.Timestamp? = nil

  /// Time when the request started processing, i.e., when the state was set to
  /// RUNNING.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The current state of the operation.
  public var state: PreviewState = PreviewState()

  /// Total number of resources that need scanning.
  /// Should equal resource_scanned + resources_pending
  public var resourcesFound: Swift.Int32 = Swift.Int32()

  /// Number of resources already scanned.
  public var resourcesScanned: Swift.Int32 = Swift.Int32()

  /// Number of resources still to scan.
  public var resourcesPending: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateOrgPolicyViolationsPreviewOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateOrgPolicyViolationsPreviewOperationMetadata().with { $0.requestTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let requestTime = CodingKeys(stringValue: "requestTime")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let state = CodingKeys(stringValue: "state")
    static let resourcesFound = CodingKeys(stringValue: "resourcesFound")
    static let resourcesScanned = CodingKeys(stringValue: "resourcesScanned")
    static let resourcesPending = CodingKeys(stringValue: "resourcesPending")

    static let _knownKeys: Set<Swift.String> = [
      "requestTime",
      "startTime",
      "state",
      "resourcesFound",
      "resourcesScanned",
      "resourcesPending",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.requestTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .requestTime)
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .startTime)
    if let value = try container.decodeIfPresent(PreviewState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .resourcesFound) {
      self.resourcesFound = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .resourcesScanned) {
      self.resourcesScanned = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .resourcesPending) {
      self.resourcesPending = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.requestTime, forKey: .requestTime)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.resourcesFound, forKey: .resourcesFound)
    try container.encode(self.resourcesScanned, forKey: .resourcesScanned)
    try container.encode(self.resourcesPending, forKey: .resourcesPending)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.policysimulator.v1.CreateOrgPolicyViolationsPreviewOperationMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
