// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// CreateOrgPolicyViolationsPreviewOperationMetadata is metadata about an
/// OrgPolicyViolationsPreview generations operation.
public struct CreateOrgPolicyViolationsPreviewOperationMetadata: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Time when the request was received.
  public var requestTime: GoogleCloudWkt.Timestamp? = nil

  /// Time when the request started processing, i.e., when the state was set to
  /// RUNNING.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The current state of the operation.
  public var state: PreviewState = PreviewState()

  /// Total number of resources that need scanning.
  /// Should equal resource_scanned + resources_pending
  public var resourcesFound: Swift.Int32 = Swift.Int32()

  /// Number of resources already scanned.
  public var resourcesScanned: Swift.Int32 = Swift.Int32()

  /// Number of resources still to scan.
  public var resourcesPending: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `CreateOrgPolicyViolationsPreviewOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateOrgPolicyViolationsPreviewOperationMetadata().with { $0.requestTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.policysimulator.v1.CreateOrgPolicyViolationsPreviewOperationMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
