// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [Simulator.CreateReplay][google.cloud.policysimulator.v1.Simulator.CreateReplay].
///
/// [google.cloud.policysimulator.v1.Simulator.CreateReplay]: <doc:Simulator/createReplay(request:)>
public struct CreateReplayRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this
  /// [Replay][google.cloud.policysimulator.v1.Replay] will be created. This
  /// resource must be a project, folder, or organization with a location.
  ///
  /// Example: `projects/my-example-project/locations/global`
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  public var parent: Swift.String = Swift.String()

  /// Required. The [Replay][google.cloud.policysimulator.v1.Replay] to create.
  /// Set `Replay.ReplayConfig` to configure the replay.
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  public var replay: Replay? = nil

  /// Initialize a new instance of `CreateReplayRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateReplayRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.CreateReplayRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
