// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// CreateOrgPolicyViolationsPreviewRequest is the request message for
/// [OrgPolicyViolationsPreviewService.CreateOrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreviewService.CreateOrgPolicyViolationsPreview].
///
/// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreviewService.CreateOrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreviewServiceClient/createOrgPolicyViolationsPreview(request:options:)>
public struct CreateOrgPolicyViolationsPreviewRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The organization under which this
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// will be created.
  ///
  /// Example: `organizations/my-example-org/locations/global`
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  public var parent: Swift.String = Swift.String()

  /// Required. The
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// to generate.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  public var orgPolicyViolationsPreview: OrgPolicyViolationsPreview? = nil

  /// Optional. An optional user-specified ID for the
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview].
  /// If not provided, a random ID will be generated.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  public var orgPolicyViolationsPreviewId: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateOrgPolicyViolationsPreviewRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateOrgPolicyViolationsPreviewRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let orgPolicyViolationsPreview = CodingKeys(stringValue: "orgPolicyViolationsPreview")
    static let orgPolicyViolationsPreviewId = CodingKeys(
      stringValue: "orgPolicyViolationsPreviewId")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "orgPolicyViolationsPreview",
      "orgPolicyViolationsPreviewId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.orgPolicyViolationsPreview = try container.decodeIfPresent(
      OrgPolicyViolationsPreview.self, forKey: .orgPolicyViolationsPreview)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .orgPolicyViolationsPreviewId)
    {
      self.orgPolicyViolationsPreviewId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(
      self.orgPolicyViolationsPreview, forKey: .orgPolicyViolationsPreview)
    try container.encode(self.orgPolicyViolationsPreviewId, forKey: .orgPolicyViolationsPreviewId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.policysimulator.v1.CreateOrgPolicyViolationsPreviewRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
