// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Details about how a set of policies, listed in
/// [ExplainedPolicy][google.cloud.policysimulator.v1.ExplainedPolicy], resulted
/// in a certain [AccessState][google.cloud.policysimulator.v1.AccessState] when
/// replaying an access tuple.
///
/// [google.cloud.policysimulator.v1.AccessState]: <doc:AccessState>
/// [google.cloud.policysimulator.v1.ExplainedPolicy]: <doc:ExplainedPolicy>
public struct ExplainedAccess: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Whether the principal in the access tuple has permission to access the
  /// resource in the access tuple under the given policies.
  public var accessState: AccessState = AccessState()

  /// If the [AccessState][google.cloud.policysimulator.v1.AccessState] is
  /// `UNKNOWN`, this field contains the policies that led to that result.
  ///
  /// If the `AccessState` is `GRANTED` or `NOT_GRANTED`, this field is
  /// omitted.
  ///
  /// [google.cloud.policysimulator.v1.AccessState]: <doc:AccessState>
  public var policies: [ExplainedPolicy] = []

  /// If the [AccessState][google.cloud.policysimulator.v1.AccessState] is
  /// `UNKNOWN`, this field contains a list of errors explaining why the result
  /// is `UNKNOWN`.
  ///
  /// If the `AccessState` is `GRANTED` or `NOT_GRANTED`, this field is
  /// omitted.
  ///
  /// [google.cloud.policysimulator.v1.AccessState]: <doc:AccessState>
  public var errors: [GoogleRpc.Status] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExplainedAccess`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExplainedAccess().with { $0.accessState = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let accessState = CodingKeys(stringValue: "accessState")
    static let policies = CodingKeys(stringValue: "policies")
    static let errors = CodingKeys(stringValue: "errors")

    static let _knownKeys: Set<Swift.String> = [
      "accessState",
      "policies",
      "errors",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(AccessState.self, forKey: .accessState) {
      self.accessState = value
    }
    if let value = try container.decodeIfPresent([ExplainedPolicy].self, forKey: .policies) {
      self.policies = value
    }
    if let value = try container.decodeIfPresent([GoogleRpc.Status].self, forKey: .errors) {
      self.errors = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.accessState, forKey: .accessState)
    try container.encode(self.policies, forKey: .policies)
    try container.encode(self.errors, forKey: .errors)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.ExplainedAccess"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
