// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ListOrgPolicyViolationsPreviewsRequest is the request message for
/// [OrgPolicyViolationsPreviewService.ListOrgPolicyViolationsPreviews][google.cloud.policysimulator.v1.OrgPolicyViolationsPreviewService.ListOrgPolicyViolationsPreviews].
///
/// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreviewService.ListOrgPolicyViolationsPreviews]: <doc:OrgPolicyViolationsPreviewService/listOrgPolicyViolationsPreviews(request:)>
public struct ListOrgPolicyViolationsPreviewsRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. The parent the violations are scoped to.
  /// Format:
  /// `organizations/{organization}/locations/{location}`
  ///
  /// Example: `organizations/my-example-org/locations/global`
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of items to return. The service may return
  /// fewer than this value. If unspecified, at most 5 items will be returned.
  /// The maximum value is 10; values above 10 will be coerced to 10.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous call. Provide this to
  /// retrieve the subsequent page.
  ///
  /// When paginating, all other parameters must match the call that provided the
  /// page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListOrgPolicyViolationsPreviewsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListOrgPolicyViolationsPreviewsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.policysimulator.v1.ListOrgPolicyViolationsPreviewsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
