// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [Simulator.ListReplayResults][google.cloud.policysimulator.v1.Simulator.ListReplayResults].
///
/// [google.cloud.policysimulator.v1.Simulator.ListReplayResults]: <doc:Simulator/listReplayResults(request:)>
public struct ListReplayResultsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The [Replay][google.cloud.policysimulator.v1.Replay] whose
  /// results are listed, in the following format:
  ///
  /// `{projects|folders|organizations}/{resource-id}/locations/global/replays/{replay-id}`
  ///
  /// Example:
  /// `projects/my-project/locations/global/replays/506a5f7f-38ce-4d7d-8e03-479ce1833c36`
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  public var parent: Swift.String = Swift.String()

  /// The maximum number of
  /// [ReplayResult][google.cloud.policysimulator.v1.ReplayResult] objects to
  /// return. Defaults to 5000.
  ///
  /// The maximum value is 5000; values above 5000 are rounded down to 5000.
  ///
  /// [google.cloud.policysimulator.v1.ReplayResult]: <doc:ReplayResult>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous
  /// [Simulator.ListReplayResults][google.cloud.policysimulator.v1.Simulator.ListReplayResults]
  /// call. Provide this token to retrieve the next page of results.
  ///
  /// When paginating, all other parameters provided to
  /// [Simulator.ListReplayResults[] must match the call that provided the page
  /// token.
  ///
  /// [google.cloud.policysimulator.v1.Simulator.ListReplayResults]: <doc:Simulator/listReplayResults(request:)>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListReplayResultsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListReplayResultsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.ListReplayResultsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
