// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// OrgPolicyViolationsPreview is a resource providing a preview of the
/// violations that will exist if an OrgPolicy change is made.
///
/// The list of violations are modeled as child resources and retrieved via a
/// [ListOrgPolicyViolations][] API call. There are potentially more
/// [OrgPolicyViolations][] than could fit in an embedded field. Thus, the use of
/// a child resource instead of a field.
public struct OrgPolicyViolationsPreview: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the `OrgPolicyViolationsPreview`. It has
  /// the following format:
  ///
  /// `organizations/{organization}/locations/{location}/orgPolicyViolationsPreviews/{orgPolicyViolationsPreview}`
  ///
  /// Example:
  /// `organizations/my-example-org/locations/global/orgPolicyViolationsPreviews/506a5f7f`
  public var name: Swift.String = Swift.String()

  /// Output only. The state of the `OrgPolicyViolationsPreview`.
  public var state: PreviewState = PreviewState()

  /// Required. The proposed changes we are previewing violations for.
  public var overlay: OrgPolicyOverlay? = nil

  /// Output only. The number of [OrgPolicyViolations][] in this
  /// `OrgPolicyViolationsPreview`. This count may differ from
  /// `resource_summary.noncompliant_count` because each
  /// [OrgPolicyViolation][google.cloud.policysimulator.v1.OrgPolicyViolation] is
  /// specific to a resource **and** constraint. If there are multiple
  /// constraints being evaluated (i.e. multiple policies in the overlay), a
  /// single resource may violate multiple constraints.
  public var violationsCount: Swift.Int32 = Swift.Int32()

  /// Output only. A summary of the state of all resources scanned for compliance
  /// with the changed OrgPolicy.
  public var resourceCounts: OrgPolicyViolationsPreview.ResourceCounts? = nil

  /// Output only. The names of the constraints against which all
  /// `OrgPolicyViolations` were evaluated.
  ///
  /// If `OrgPolicyOverlay` only contains `PolicyOverlay` then it contains
  /// the name of the configured custom constraint, applicable to the specified
  /// policies. Otherwise it contains the name of the constraint specified in
  /// `CustomConstraintOverlay`.
  ///
  /// Format:
  /// `organizations/{organization_id}/customConstraints/{custom_constraint_id}`
  ///
  /// Example: `organizations/123/customConstraints/custom.createOnlyE2TypeVms`
  public var customConstraints: [Swift.String] = []

  /// Output only. Time when this `OrgPolicyViolationsPreview` was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `OrgPolicyViolationsPreview`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OrgPolicyViolationsPreview().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A summary of the state of all resources scanned for compliance with the
  /// changed OrgPolicy.
  public struct ResourceCounts: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. Number of resources checked for compliance.
    ///
    /// Must equal:  unenforced + noncompliant + compliant + error
    public var scanned: Swift.Int32 = Swift.Int32()

    /// Output only. Number of scanned resources with at least one violation.
    public var noncompliant: Swift.Int32 = Swift.Int32()

    /// Output only. Number of scanned resources with zero violations.
    public var compliant: Swift.Int32 = Swift.Int32()

    /// Output only. Number of resources where the constraint was not enforced,
    /// i.e. the Policy set `enforced: false` for that resource.
    public var unenforced: Swift.Int32 = Swift.Int32()

    /// Output only. Number of resources that returned an error when scanned.
    public var errors: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `ResourceCounts`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceCounts().with { $0.scanned = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policysimulator.v1.OrgPolicyViolationsPreview.ResourceCounts"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.OrgPolicyViolationsPreview"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
