// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudOrgPolicyV2
import GoogleCloudWkt
import GoogleRpc

/// OrgPolicyViolation is a resource representing a single resource violating a
/// single OrgPolicy constraint.
public struct OrgPolicyViolation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the `OrgPolicyViolation`. Example:
  /// organizations/my-example-org/locations/global/orgPolicyViolationsPreviews/506a5f7f/orgPolicyViolations/38ce`
  public var name: Swift.String = Swift.String()

  /// The resource violating the constraint.
  public var resource: ResourceContext? = nil

  /// The custom constraint being violated.
  public var customConstraint: GoogleCloudOrgPolicyV2.CustomConstraint? = nil

  /// Any error encountered during the evaluation.
  public var error: GoogleRpc.Status? = nil

  /// Initialize a new instance of `OrgPolicyViolation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OrgPolicyViolation().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.OrgPolicyViolation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
