// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class OrgPolicyViolationsPreviewServiceRetry: OrgPolicyViolationsPreviewServiceStub {
    let inner: any OrgPolicyViolationsPreviewServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(
      _ inner: any OrgPolicyViolationsPreviewServiceStub, options: GoogleCloudGax.ClientOptions
    ) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listOrgPolicyViolationsPreviews(
      request: ListOrgPolicyViolationsPreviewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListOrgPolicyViolationsPreviewsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse
          in
          return try await self.inner.listOrgPolicyViolationsPreviews(request: r, options: o)
        })
    }

    public func getOrgPolicyViolationsPreview(
      request: GetOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetOrgPolicyViolationsPreviewRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview
          in
          return try await self.inner.getOrgPolicyViolationsPreview(request: r, options: o)
        })
    }

    public func createOrgPolicyViolationsPreview(
      request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateOrgPolicyViolationsPreviewRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.Operation
          in
          return try await self.inner.createOrgPolicyViolationsPreview(request: r, options: o)
        })
    }

    public func listOrgPolicyViolations(
      request: ListOrgPolicyViolationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListOrgPolicyViolationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse
          in
          return try await self.inner.listOrgPolicyViolations(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
