// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Violations Preview API service for OrgPolicy.
///
/// An
/// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
/// is a preview of the violations that will exist as soon as a proposed
/// OrgPolicy change is submitted. To create an
/// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview],
/// the API user specifies the changes they wish to make and requests the
/// generation of a preview via [GenerateViolationsPreview][]. the OrgPolicy
/// Simulator service then scans the API user's currently existing resources to
/// determine these resources violate the newly set OrgPolicy.
///
/// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
///
/// @Snippet(path: "OrgPolicyViolationsPreviewServiceQuickstart")
public final class OrgPolicyViolationsPreviewServiceClient: Clients
    .OrgPolicyViolationsPreviewServiceProtocol, Sendable
{
  let inner: any Clients.OrgPolicyViolationsPreviewServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `OrgPolicyViolationsPreviewServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.OrgPolicyViolationsPreviewServiceStub =
      try Clients.OrgPolicyViolationsPreviewServiceTransport(options)
    inner = Clients.OrgPolicyViolationsPreviewServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OrgPolicyViolationsPreviewServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// ListOrgPolicyViolationsPreviews lists each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// in an organization. Each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// is available for at least 7 days.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOrgPolicyViolationsPreviews")
  public func listOrgPolicyViolationsPreviews(
    request: ListOrgPolicyViolationsPreviewsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse {
    try await self.inner.listOrgPolicyViolationsPreviews(request: request, options: options)
  }

  /// GetOrgPolicyViolationsPreview gets the specified
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview].
  /// Each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// is available for at least 7 days.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_GetOrgPolicyViolationsPreview")
  public func getOrgPolicyViolationsPreview(
    request: GetOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview {
    try await self.inner.getOrgPolicyViolationsPreview(request: request, options: options)
  }

  /// CreateOrgPolicyViolationsPreview creates an
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// for the proposed changes in the provided
  /// [OrgPolicyViolationsPreview.OrgPolicyOverlay][]. The changes to OrgPolicy
  /// are specified by this `OrgPolicyOverlay`. The resources to scan are
  /// inferred from these specified changes.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_CreateOrgPolicyViolationsPreview")
  public func createOrgPolicyViolationsPreview(
    request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createOrgPolicyViolationsPreview(request: request, options: options)
  }

  /// CreateOrgPolicyViolationsPreview creates an
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// for the proposed changes in the provided
  /// [OrgPolicyViolationsPreview.OrgPolicyOverlay][]. The changes to OrgPolicy
  /// are specified by this `OrgPolicyOverlay`. The resources to scan are
  /// inferred from these specified changes.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_CreateOrgPolicyViolationsPreview")
  public func createOrgPolicyViolationsPreviewPollingUntilDone(
    request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<OrgPolicyViolationsPreview> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<OrgPolicyViolationsPreview>.State in
      return try op._extractStatus(OrgPolicyViolationsPreview.self)
    }
    let rawOp = try await self.createOrgPolicyViolationsPreview(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<OrgPolicyViolationsPreview>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// ListOrgPolicyViolations lists the [OrgPolicyViolations][] that are present
  /// in an
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview].
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOrgPolicyViolations")
  public func listOrgPolicyViolations(
    request: ListOrgPolicyViolationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse {
    try await self.inner.listOrgPolicyViolations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OrgPolicyViolationsPreviewServiceClient`.
  ///
  /// To mock `OrgPolicyViolationsPreviewServiceClient` change your functions to receive
  /// `some OrgPolicyViolationsPreviewServiceProtocol` or `any OrgPolicyViolationsPreviewServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OrgPolicyViolationsPreviewServiceProtocol: Sendable {
    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreviewPollingUntilDone(
      request: CreateOrgPolicyViolationsPreviewRequest
    ) async throws -> any GoogleGax.PollableOperation<OrgPolicyViolationsPreview>

    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreviewPollingUntilDone(
      parent: Swift.String,
      orgPolicyViolationsPreview: OrgPolicyViolationsPreview?,
      orgPolicyViolationsPreviewId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<OrgPolicyViolationsPreview>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolationsPreviews`.
    func listOrgPolicyViolationsPreviews(
      request: ListOrgPolicyViolationsPreviewsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse

    /// See `OrgPolicyViolationsPreviewServiceClient.getOrgPolicyViolationsPreview`.
    func getOrgPolicyViolationsPreview(
      request: GetOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview

    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreview(
      request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreviewPollingUntilDone(
      request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<OrgPolicyViolationsPreview>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolations`.
    func listOrgPolicyViolations(
      request: ListOrgPolicyViolationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse

    /// See `OrgPolicyViolationsPreviewServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.OrgPolicyViolationsPreviewServiceProtocol {
  public func listOrgPolicyViolationsPreviews(request: ListOrgPolicyViolationsPreviewsRequest)
    async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse
  {
    try await self.listOrgPolicyViolationsPreviews(request: request, options: .init())
  }

  public func listOrgPolicyViolationsPreviews(
    request: ListOrgPolicyViolationsPreviewsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOrgPolicyViolationsPreviewsByItems(
    request: ListOrgPolicyViolationsPreviewsRequest
  ) -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error> {
    self.listOrgPolicyViolationsPreviewsByItems(request: request, options: .init())
  }

  /// ListOrgPolicyViolationsPreviews lists each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// in an organization. Each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// is available for at least 7 days.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOrgPolicyViolationsPreviews")
  public func listOrgPolicyViolationsPreviewsByItems(
    request: ListOrgPolicyViolationsPreviewsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOrgPolicyViolationsPreviews(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOrgPolicyViolationsPreviewsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error> {
    let request = ListOrgPolicyViolationsPreviewsRequest().with {
      $0.parent = parent
    }
    return self.listOrgPolicyViolationsPreviewsByItems(request: request)
  }

  public func getOrgPolicyViolationsPreview(request: GetOrgPolicyViolationsPreviewRequest)
    async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview
  {
    try await self.getOrgPolicyViolationsPreview(request: request, options: .init())
  }

  public func getOrgPolicyViolationsPreview(
    request: GetOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOrgPolicyViolationsPreview(
    name: Swift.String,
  ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview {
    let request = GetOrgPolicyViolationsPreviewRequest().with {
      $0.name = name
    }
    return try await self.getOrgPolicyViolationsPreview(request: request)
  }

  public func createOrgPolicyViolationsPreview(request: CreateOrgPolicyViolationsPreviewRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.createOrgPolicyViolationsPreview(request: request, options: .init())
  }

  public func createOrgPolicyViolationsPreview(
    request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createOrgPolicyViolationsPreviewPollingUntilDone(
    request: CreateOrgPolicyViolationsPreviewRequest
  ) async throws -> any GoogleGax.PollableOperation<OrgPolicyViolationsPreview> {
    try await self.createOrgPolicyViolationsPreviewPollingUntilDone(
      request: request, options: .init())
  }

  public func createOrgPolicyViolationsPreviewPollingUntilDone(
    request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<OrgPolicyViolationsPreview> {
    let poll = {
      () async throws -> GoogleGax._PollableOperationImpl<OrgPolicyViolationsPreview>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createOrgPolicyViolationsPreviewPollingUntilDone(
    parent: Swift.String,
    orgPolicyViolationsPreview: OrgPolicyViolationsPreview?,
    orgPolicyViolationsPreviewId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<OrgPolicyViolationsPreview> {
    let request = CreateOrgPolicyViolationsPreviewRequest().with {
      $0.parent = parent
      $0.orgPolicyViolationsPreview = orgPolicyViolationsPreview
      $0.orgPolicyViolationsPreviewId = orgPolicyViolationsPreviewId
    }
    return try await self.createOrgPolicyViolationsPreviewPollingUntilDone(request: request)
  }

  public func listOrgPolicyViolations(request: ListOrgPolicyViolationsRequest) async throws
    -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse
  {
    try await self.listOrgPolicyViolations(request: request, options: .init())
  }

  public func listOrgPolicyViolations(
    request: ListOrgPolicyViolationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOrgPolicyViolationsByItems(
    request: ListOrgPolicyViolationsRequest
  ) -> any AsyncSequence<OrgPolicyViolation, Swift.Error> {
    self.listOrgPolicyViolationsByItems(request: request, options: .init())
  }

  /// ListOrgPolicyViolations lists the [OrgPolicyViolations][] that are present
  /// in an
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview].
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOrgPolicyViolations")
  public func listOrgPolicyViolationsByItems(
    request: ListOrgPolicyViolationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<OrgPolicyViolation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOrgPolicyViolations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOrgPolicyViolationsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<OrgPolicyViolation, Swift.Error> {
    let request = ListOrgPolicyViolationsRequest().with {
      $0.parent = parent
    }
    return self.listOrgPolicyViolationsByItems(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
