// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Violations Preview API service for OrgPolicy.
///
/// An
/// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
/// is a preview of the violations that will exist as soon as a proposed
/// OrgPolicy change is submitted. To create an
/// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview],
/// the API user specifies the changes they wish to make and requests the
/// generation of a preview via [GenerateViolationsPreview][]. the OrgPolicy
/// Simulator service then scans the API user's currently existing resources to
/// determine these resources violate the newly set OrgPolicy.
///
/// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
///
/// @Snippet(path: "OrgPolicyViolationsPreviewServiceQuickstart")
public class OrgPolicyViolationsPreviewServiceClient: Clients
    .OrgPolicyViolationsPreviewServiceProtocol
{
  let inner: any Clients.OrgPolicyViolationsPreviewServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `OrgPolicyViolationsPreviewServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.OrgPolicyViolationsPreviewServiceStub =
      try Clients.OrgPolicyViolationsPreviewServiceTransport(options)
    inner = Clients.OrgPolicyViolationsPreviewServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.OrgPolicyViolationsPreviewServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// ListOrgPolicyViolationsPreviews lists each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// in an organization. Each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// is available for at least 7 days.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOrgPolicyViolationsPreviews")
  public func listOrgPolicyViolationsPreviews(
    request: ListOrgPolicyViolationsPreviewsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse {
    try await self.inner.listOrgPolicyViolationsPreviews(request: request, options: options)
  }

  /// ListOrgPolicyViolationsPreviews lists each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// in an organization. Each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// is available for at least 7 days.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOrgPolicyViolationsPreviews")
  public func listOrgPolicyViolationsPreviews(
    byItem: ListOrgPolicyViolationsPreviewsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOrgPolicyViolationsPreviews(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// GetOrgPolicyViolationsPreview gets the specified
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview].
  /// Each
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// is available for at least 7 days.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_GetOrgPolicyViolationsPreview")
  public func getOrgPolicyViolationsPreview(
    request: GetOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview {
    try await self.inner.getOrgPolicyViolationsPreview(request: request, options: options)
  }

  /// CreateOrgPolicyViolationsPreview creates an
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// for the proposed changes in the provided
  /// [OrgPolicyViolationsPreview.OrgPolicyOverlay][]. The changes to OrgPolicy
  /// are specified by this `OrgPolicyOverlay`. The resources to scan are
  /// inferred from these specified changes.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_CreateOrgPolicyViolationsPreview")
  public func createOrgPolicyViolationsPreview(
    request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createOrgPolicyViolationsPreview(request: request, options: options)
  }

  /// CreateOrgPolicyViolationsPreview creates an
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// for the proposed changes in the provided
  /// [OrgPolicyViolationsPreview.OrgPolicyOverlay][]. The changes to OrgPolicy
  /// are specified by this `OrgPolicyOverlay`. The resources to scan are
  /// inferred from these specified changes.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_CreateOrgPolicyViolationsPreview")
  public func createOrgPolicyViolationsPreview(
    withPolling: CreateOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<OrgPolicyViolationsPreview> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<OrgPolicyViolationsPreview>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try OrgPolicyViolationsPreview(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createOrgPolicyViolationsPreview(
      request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<OrgPolicyViolationsPreview>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// ListOrgPolicyViolations lists the [OrgPolicyViolations][] that are present
  /// in an
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview].
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOrgPolicyViolations")
  public func listOrgPolicyViolations(
    request: ListOrgPolicyViolationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse {
    try await self.inner.listOrgPolicyViolations(request: request, options: options)
  }

  /// ListOrgPolicyViolations lists the [OrgPolicyViolations][] that are present
  /// in an
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview].
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOrgPolicyViolations")
  public func listOrgPolicyViolations(
    byItem: ListOrgPolicyViolationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<OrgPolicyViolation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOrgPolicyViolations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "OrgPolicyViolationsPreviewService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `OrgPolicyViolationsPreviewServiceClient`.
  ///
  /// To mock `OrgPolicyViolationsPreviewServiceClient` change your functions to receive
  /// `some OrgPolicyViolationsPreviewServiceProtocol` or `any OrgPolicyViolationsPreviewServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol OrgPolicyViolationsPreviewServiceProtocol {
    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolationsPreviews`.
    func listOrgPolicyViolationsPreviews(request: ListOrgPolicyViolationsPreviewsRequest)
      async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolationsPreviews`.
    func listOrgPolicyViolationsPreviews(
      byItem: ListOrgPolicyViolationsPreviewsRequest
    ) throws -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolationsPreviews`.
    func listOrgPolicyViolationsPreviews(
      parent: Swift.String,
    ) throws -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error>

    /// See `OrgPolicyViolationsPreviewServiceClient.getOrgPolicyViolationsPreview`.
    func getOrgPolicyViolationsPreview(request: GetOrgPolicyViolationsPreviewRequest) async throws
      -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview

    /// See `OrgPolicyViolationsPreviewServiceClient.getOrgPolicyViolationsPreview`.
    func getOrgPolicyViolationsPreview(
      name: Swift.String,
    ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview

    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreview(request: CreateOrgPolicyViolationsPreviewRequest)
      async throws -> GoogleLongRunning.Operation

    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreview(withPolling: CreateOrgPolicyViolationsPreviewRequest)
      async throws -> any GoogleCloudGax.PollableOperation<OrgPolicyViolationsPreview>

    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreview(
      parent: Swift.String,
      orgPolicyViolationsPreview: OrgPolicyViolationsPreview?,
      orgPolicyViolationsPreviewId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<OrgPolicyViolationsPreview>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolations`.
    func listOrgPolicyViolations(request: ListOrgPolicyViolationsRequest) async throws
      -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolations`.
    func listOrgPolicyViolations(
      byItem: ListOrgPolicyViolationsRequest
    ) throws -> any AsyncSequence<OrgPolicyViolation, Swift.Error>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolations`.
    func listOrgPolicyViolations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<OrgPolicyViolation, Swift.Error>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `OrgPolicyViolationsPreviewServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolationsPreviews`.
    func listOrgPolicyViolationsPreviews(
      request: ListOrgPolicyViolationsPreviewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolationsPreviews`.
    func listOrgPolicyViolationsPreviews(
      byItem: ListOrgPolicyViolationsPreviewsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error>

    /// See `OrgPolicyViolationsPreviewServiceClient.getOrgPolicyViolationsPreview`.
    func getOrgPolicyViolationsPreview(
      request: GetOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview

    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreview(
      request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `OrgPolicyViolationsPreviewServiceClient.createOrgPolicyViolationsPreview`.
    func createOrgPolicyViolationsPreview(
      withPolling: CreateOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<OrgPolicyViolationsPreview>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolations`.
    func listOrgPolicyViolations(
      request: ListOrgPolicyViolationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse

    /// See `OrgPolicyViolationsPreviewServiceClient.listOrgPolicyViolations`.
    func listOrgPolicyViolations(
      byItem: ListOrgPolicyViolationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<OrgPolicyViolation, Swift.Error>

    /// See `OrgPolicyViolationsPreviewServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `OrgPolicyViolationsPreviewServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>
  }
}

// Default implementations
extension Clients.OrgPolicyViolationsPreviewServiceProtocol {
  public func listOrgPolicyViolationsPreviews(request: ListOrgPolicyViolationsPreviewsRequest)
    async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse
  {
    try await self.listOrgPolicyViolationsPreviews(request: request, options: .init())
  }

  public func listOrgPolicyViolationsPreviews(
    request: ListOrgPolicyViolationsPreviewsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOrgPolicyViolationsPreviews(
    byItem: ListOrgPolicyViolationsPreviewsRequest
  ) throws -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error> {
    try self.listOrgPolicyViolationsPreviews(byItem: byItem, options: .init())
  }

  public func listOrgPolicyViolationsPreviews(
    byItem: ListOrgPolicyViolationsPreviewsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsPreviewsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOrgPolicyViolationsPreviews(
    parent: Swift.String,
  ) throws -> any AsyncSequence<OrgPolicyViolationsPreview, Swift.Error> {
    let request = ListOrgPolicyViolationsPreviewsRequest().with {
      $0.parent = parent
    }
    return try self.listOrgPolicyViolationsPreviews(byItem: request)
  }

  public func getOrgPolicyViolationsPreview(request: GetOrgPolicyViolationsPreviewRequest)
    async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview
  {
    try await self.getOrgPolicyViolationsPreview(request: request, options: .init())
  }

  public func getOrgPolicyViolationsPreview(
    request: GetOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOrgPolicyViolationsPreview(
    name: Swift.String,
  ) async throws -> GoogleCloudPolicySimulatorV1.OrgPolicyViolationsPreview {
    let request = GetOrgPolicyViolationsPreviewRequest().with {
      $0.name = name
    }
    return try await self.getOrgPolicyViolationsPreview(request: request)
  }

  public func createOrgPolicyViolationsPreview(request: CreateOrgPolicyViolationsPreviewRequest)
    async throws -> GoogleLongRunning.Operation
  {
    try await self.createOrgPolicyViolationsPreview(request: request, options: .init())
  }

  public func createOrgPolicyViolationsPreview(
    request: CreateOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createOrgPolicyViolationsPreview(withPolling: CreateOrgPolicyViolationsPreviewRequest)
    async throws -> any GoogleCloudGax.PollableOperation<OrgPolicyViolationsPreview>
  {
    try await self.createOrgPolicyViolationsPreview(withPolling: withPolling, options: .init())
  }

  public func createOrgPolicyViolationsPreview(
    withPolling: CreateOrgPolicyViolationsPreviewRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<OrgPolicyViolationsPreview> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<OrgPolicyViolationsPreview>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createOrgPolicyViolationsPreview(
    parent: Swift.String,
    orgPolicyViolationsPreview: OrgPolicyViolationsPreview?,
    orgPolicyViolationsPreviewId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<OrgPolicyViolationsPreview> {
    let request = CreateOrgPolicyViolationsPreviewRequest().with {
      $0.parent = parent
      $0.orgPolicyViolationsPreview = orgPolicyViolationsPreview
      $0.orgPolicyViolationsPreviewId = orgPolicyViolationsPreviewId
    }
    return try await self.createOrgPolicyViolationsPreview(withPolling: request)
  }

  public func listOrgPolicyViolations(request: ListOrgPolicyViolationsRequest) async throws
    -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse
  {
    try await self.listOrgPolicyViolations(request: request, options: .init())
  }

  public func listOrgPolicyViolations(
    request: ListOrgPolicyViolationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOrgPolicyViolations(
    byItem: ListOrgPolicyViolationsRequest
  ) throws -> any AsyncSequence<OrgPolicyViolation, Swift.Error> {
    try self.listOrgPolicyViolations(byItem: byItem, options: .init())
  }

  public func listOrgPolicyViolations(
    byItem: ListOrgPolicyViolationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<OrgPolicyViolation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudPolicySimulatorV1.ListOrgPolicyViolationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOrgPolicyViolations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<OrgPolicyViolation, Swift.Error> {
    let request = ListOrgPolicyViolationsRequest().with {
      $0.parent = parent
    }
    return try self.listOrgPolicyViolations(byItem: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
