// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleCloudOrgPolicyV2
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The proposed changes to OrgPolicy.
public struct OrgPolicyOverlay: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The OrgPolicy changes to preview violations for.
  ///
  /// Any existing OrgPolicies with the same name will be overridden
  /// in the simulation. That is, violations will be determined as if all
  /// policies in the overlay were created or updated.
  public var policies: [OrgPolicyOverlay.PolicyOverlay] = []

  /// Optional. The OrgPolicy CustomConstraint changes to preview violations for.
  ///
  /// Any existing CustomConstraints with the same name will be overridden
  /// in the simulation. That is, violations will be determined as if all
  /// custom constraints in the overlay were instantiated.
  ///
  /// Only a single custom_constraint is supported in the overlay at a time.
  /// For evaluating multiple constraints, multiple
  /// `GenerateOrgPolicyViolationsPreview` requests are made, where each request
  /// evaluates a single constraint.
  public var customConstraints: [OrgPolicyOverlay.CustomConstraintOverlay] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OrgPolicyOverlay`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OrgPolicyOverlay().with { $0.policies = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let policies = CodingKeys(stringValue: "policies")
    static let customConstraints = CodingKeys(stringValue: "customConstraints")

    static let _knownKeys: Set<Swift.String> = [
      "policies",
      "customConstraints",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [OrgPolicyOverlay.PolicyOverlay].self, forKey: .policies)
    {
      self.policies = value
    }
    if let value = try container.decodeIfPresent(
      [OrgPolicyOverlay.CustomConstraintOverlay].self, forKey: .customConstraints)
    {
      self.customConstraints = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.policies, forKey: .policies)
    try container.encode(self.customConstraints, forKey: .customConstraints)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A change to an OrgPolicy.
  public struct PolicyOverlay: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The parent of the policy we are attaching to.
    /// Example: "projects/123456"
    public var policyParent: Swift.String = Swift.String()

    /// Optional. The new or updated OrgPolicy.
    public var policy: GoogleCloudOrgPolicyV2.Policy? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PolicyOverlay`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PolicyOverlay().with { $0.policyParent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let policyParent = CodingKeys(stringValue: "policyParent")
      static let policy = CodingKeys(stringValue: "policy")

      static let _knownKeys: Set<Swift.String> = [
        "policyParent",
        "policy",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .policyParent) {
        self.policyParent = value
      }
      self.policy = try container.decodeIfPresent(
        GoogleCloudOrgPolicyV2.Policy.self, forKey: .policy)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.policyParent, forKey: .policyParent)
      try container.encodeIfPresent(self.policy, forKey: .policy)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.policysimulator.v1.OrgPolicyOverlay.PolicyOverlay"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A change to an OrgPolicy custom constraint.
  public struct CustomConstraintOverlay: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Resource the constraint is attached to.
    /// Example: "organization/987654"
    public var customConstraintParent: Swift.String = Swift.String()

    /// Optional. The new or updated custom constraint.
    public var customConstraint: GoogleCloudOrgPolicyV2.CustomConstraint? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CustomConstraintOverlay`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomConstraintOverlay().with { $0.customConstraintParent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let customConstraintParent = CodingKeys(stringValue: "customConstraintParent")
      static let customConstraint = CodingKeys(stringValue: "customConstraint")

      static let _knownKeys: Set<Swift.String> = [
        "customConstraintParent",
        "customConstraint",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .customConstraintParent)
      {
        self.customConstraintParent = value
      }
      self.customConstraint = try container.decodeIfPresent(
        GoogleCloudOrgPolicyV2.CustomConstraint.self, forKey: .customConstraint)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.customConstraintParent, forKey: .customConstraintParent)
      try container.encodeIfPresent(self.customConstraint, forKey: .customConstraint)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policysimulator.v1.OrgPolicyOverlay.CustomConstraintOverlay"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.OrgPolicyOverlay"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
