// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// OrgPolicyViolationsPreview is a resource providing a preview of the
/// violations that will exist if an OrgPolicy change is made.
///
/// The list of violations are modeled as child resources and retrieved via a
/// [ListOrgPolicyViolations][] API call. There are potentially more
/// [OrgPolicyViolations][] than could fit in an embedded field. Thus, the use of
/// a child resource instead of a field.
public struct OrgPolicyViolationsPreview: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the `OrgPolicyViolationsPreview`. It has
  /// the following format:
  ///
  /// `organizations/{organization}/locations/{location}/orgPolicyViolationsPreviews/{orgPolicyViolationsPreview}`
  ///
  /// Example:
  /// `organizations/my-example-org/locations/global/orgPolicyViolationsPreviews/506a5f7f`
  public var name: Swift.String = Swift.String()

  /// Output only. The state of the `OrgPolicyViolationsPreview`.
  public var state: PreviewState = PreviewState()

  /// Required. The proposed changes we are previewing violations for.
  public var overlay: OrgPolicyOverlay? = nil

  /// Output only. The number of [OrgPolicyViolations][] in this
  /// `OrgPolicyViolationsPreview`. This count may differ from
  /// `resource_summary.noncompliant_count` because each
  /// [OrgPolicyViolation][google.cloud.policysimulator.v1.OrgPolicyViolation] is
  /// specific to a resource **and** constraint. If there are multiple
  /// constraints being evaluated (i.e. multiple policies in the overlay), a
  /// single resource may violate multiple constraints.
  public var violationsCount: Swift.Int32 = Swift.Int32()

  /// Output only. A summary of the state of all resources scanned for compliance
  /// with the changed OrgPolicy.
  public var resourceCounts: OrgPolicyViolationsPreview.ResourceCounts? = nil

  /// Output only. The names of the constraints against which all
  /// `OrgPolicyViolations` were evaluated.
  ///
  /// If `OrgPolicyOverlay` only contains `PolicyOverlay` then it contains
  /// the name of the configured custom constraint, applicable to the specified
  /// policies. Otherwise it contains the name of the constraint specified in
  /// `CustomConstraintOverlay`.
  ///
  /// Format:
  /// `organizations/{organization_id}/customConstraints/{custom_constraint_id}`
  ///
  /// Example: `organizations/123/customConstraints/custom.createOnlyE2TypeVms`
  public var customConstraints: [Swift.String] = []

  /// Output only. Time when this `OrgPolicyViolationsPreview` was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `OrgPolicyViolationsPreview`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OrgPolicyViolationsPreview().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let state = CodingKeys(stringValue: "state")
    static let overlay = CodingKeys(stringValue: "overlay")
    static let violationsCount = CodingKeys(stringValue: "violationsCount")
    static let resourceCounts = CodingKeys(stringValue: "resourceCounts")
    static let customConstraints = CodingKeys(stringValue: "customConstraints")
    static let createTime = CodingKeys(stringValue: "createTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "state",
      "overlay",
      "violationsCount",
      "resourceCounts",
      "customConstraints",
      "createTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(PreviewState.self, forKey: .state) {
      self.state = value
    }
    self.overlay = try container.decodeIfPresent(OrgPolicyOverlay.self, forKey: .overlay)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .violationsCount) {
      self.violationsCount = value
    }
    self.resourceCounts = try container.decodeIfPresent(
      OrgPolicyViolationsPreview.ResourceCounts.self, forKey: .resourceCounts)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .customConstraints) {
      self.customConstraints = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.overlay, forKey: .overlay)
    try container.encode(self.violationsCount, forKey: .violationsCount)
    try container.encodeIfPresent(self.resourceCounts, forKey: .resourceCounts)
    try container.encode(self.customConstraints, forKey: .customConstraints)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A summary of the state of all resources scanned for compliance with the
  /// changed OrgPolicy.
  public struct ResourceCounts: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. Number of resources checked for compliance.
    ///
    /// Must equal:  unenforced + noncompliant + compliant + error
    public var scanned: Swift.Int32 = Swift.Int32()

    /// Output only. Number of scanned resources with at least one violation.
    public var noncompliant: Swift.Int32 = Swift.Int32()

    /// Output only. Number of scanned resources with zero violations.
    public var compliant: Swift.Int32 = Swift.Int32()

    /// Output only. Number of resources where the constraint was not enforced,
    /// i.e. the Policy set `enforced: false` for that resource.
    public var unenforced: Swift.Int32 = Swift.Int32()

    /// Output only. Number of resources that returned an error when scanned.
    public var errors: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ResourceCounts`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceCounts().with { $0.scanned = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let scanned = CodingKeys(stringValue: "scanned")
      static let noncompliant = CodingKeys(stringValue: "noncompliant")
      static let compliant = CodingKeys(stringValue: "compliant")
      static let unenforced = CodingKeys(stringValue: "unenforced")
      static let errors = CodingKeys(stringValue: "errors")

      static let _knownKeys: Set<Swift.String> = [
        "scanned",
        "noncompliant",
        "compliant",
        "unenforced",
        "errors",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .scanned) {
        self.scanned = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .noncompliant) {
        self.noncompliant = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .compliant) {
        self.compliant = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .unenforced) {
        self.unenforced = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .errors) {
        self.errors = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.scanned, forKey: .scanned)
      try container.encode(self.noncompliant, forKey: .noncompliant)
      try container.encode(self.compliant, forKey: .compliant)
      try container.encode(self.unenforced, forKey: .unenforced)
      try container.encode(self.errors, forKey: .errors)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.policysimulator.v1.OrgPolicyViolationsPreview.ResourceCounts"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.OrgPolicyViolationsPreview"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
