// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The current state of an
/// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview].
///
/// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
public enum PreviewState: Codable, Equatable, Sendable {
  /// The state is unspecified.
  case unspecified
  /// The
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// has not been created yet.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  case previewPending
  /// The
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// is currently being created.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  case previewRunning
  /// The
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// creation finished successfully.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  case previewSucceeded
  /// The
  /// [OrgPolicyViolationsPreview][google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]
  /// creation failed with an error.
  ///
  /// [google.cloud.policysimulator.v1.OrgPolicyViolationsPreview]: <doc:OrgPolicyViolationsPreview>
  case previewFailed
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .previewPending: return 1
    case .previewRunning: return 2
    case .previewSucceeded: return 3
    case .previewFailed: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "PREVIEW_STATE_UNSPECIFIED"
    case .previewPending: return "PREVIEW_PENDING"
    case .previewRunning: return "PREVIEW_RUNNING"
    case .previewSucceeded: return "PREVIEW_SUCCEEDED"
    case .previewFailed: return "PREVIEW_FAILED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PreviewState/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "PREVIEW_STATE_UNSPECIFIED": self = .unspecified
    case "PREVIEW_PENDING": self = .previewPending
    case "PREVIEW_RUNNING": self = .previewRunning
    case "PREVIEW_SUCCEEDED": self = .previewSucceeded
    case "PREVIEW_FAILED": self = .previewFailed
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PreviewState/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .previewPending
    case 2: self = .previewRunning
    case 3: self = .previewSucceeded
    case 4: self = .previewFailed
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .previewPending: return try container.encode(1)
    case .previewRunning: return try container.encode(2)
    case .previewSucceeded: return try container.encode(3)
    case .previewFailed: return try container.encode(4)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
