// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
public import GoogleType
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The result of replaying a single access tuple against a simulated state.
public struct ReplayResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the `ReplayResult`, in the following format:
  ///
  /// `{projects|folders|organizations}/{resource-id}/locations/global/replays/{replay-id}/results/{replay-result-id}`,
  /// where `{resource-id}` is the ID of the project, folder, or organization
  /// that owns the [Replay][google.cloud.policysimulator.v1.Replay].
  ///
  /// Example:
  /// `projects/my-example-project/locations/global/replays/506a5f7f-38ce-4d7d-8e03-479ce1833c36/results/1234`
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  public var name: Swift.String = Swift.String()

  /// The [Replay][google.cloud.policysimulator.v1.Replay] that the access tuple
  /// was included in.
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  public var parent: Swift.String = Swift.String()

  /// The access tuple that was replayed. This field includes information about
  /// the principal, resource, and permission that were involved in the access
  /// attempt.
  public var accessTuple: AccessTuple? = nil

  /// The latest date this access tuple was seen in the logs.
  public var lastSeenDate: GoogleType.Date? = nil

  /// The result of replaying the access tuple.
  public var result: ResultOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReplayResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplayResult().with { $0.diff = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let diff = CodingKeys(stringValue: "diff")
    static let error = CodingKeys(stringValue: "error")
    static let name = CodingKeys(stringValue: "name")
    static let parent = CodingKeys(stringValue: "parent")
    static let accessTuple = CodingKeys(stringValue: "accessTuple")
    static let lastSeenDate = CodingKeys(stringValue: "lastSeenDate")

    static let _knownKeys: Set<Swift.String> = [
      "diff",
      "error",
      "name",
      "parent",
      "accessTuple",
      "lastSeenDate",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.accessTuple = try container.decodeIfPresent(AccessTuple.self, forKey: .accessTuple)
    self.lastSeenDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .lastSeenDate)

    var result: ResultOneOf? = nil
    let resultCheckAndSet = {
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = $0
    }
    if let diff = try container.decodeIfPresent(ReplayDiff?.self, forKey: .diff) {
      try resultCheckAndSet(.diff(diff))
    }
    if let error = try container.decodeIfPresent(GoogleRpc.Status?.self, forKey: .error) {
      try resultCheckAndSet(.error(error))
    }
    self.result = result
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.accessTuple, forKey: .accessTuple)
    try container.encodeIfPresent(self.lastSeenDate, forKey: .lastSeenDate)

    if let choice = self.result {
      switch choice {
      case .diff(let value):
        try container.encode(value, forKey: .diff)
      case .error(let value):
        try container.encode(value, forKey: .error)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The result of replaying the access tuple.
  public enum ResultOneOf: Codable, Equatable, Sendable {
    /// The difference between the principal's access under the current
    /// (baseline) policies and the principal's access under the proposed
    /// (simulated) policies.
    ///
    /// This field is only included for access tuples that were successfully
    /// replayed and had different results under the current policies and the
    /// proposed policies.
    indirect case diff(ReplayDiff?)
    /// The error that caused the access tuple replay to fail.
    ///
    /// This field is only included for access tuples that were not replayed
    /// successfully.
    indirect case error(GoogleRpc.Status?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.ReplayResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
