// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc
import GoogleType

/// The result of replaying a single access tuple against a simulated state.
public struct ReplayResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the `ReplayResult`, in the following format:
  ///
  /// `{projects|folders|organizations}/{resource-id}/locations/global/replays/{replay-id}/results/{replay-result-id}`,
  /// where `{resource-id}` is the ID of the project, folder, or organization
  /// that owns the [Replay][google.cloud.policysimulator.v1.Replay].
  ///
  /// Example:
  /// `projects/my-example-project/locations/global/replays/506a5f7f-38ce-4d7d-8e03-479ce1833c36/results/1234`
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  public var name: Swift.String = Swift.String()

  /// The [Replay][google.cloud.policysimulator.v1.Replay] that the access tuple
  /// was included in.
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  public var parent: Swift.String = Swift.String()

  /// The access tuple that was replayed. This field includes information about
  /// the principal, resource, and permission that were involved in the access
  /// attempt.
  public var accessTuple: AccessTuple? = nil

  /// The latest date this access tuple was seen in the logs.
  public var lastSeenDate: GoogleType.Date? = nil

  /// The result of replaying the access tuple.
  public var result: OneOf_Result? = nil

  /// Initialize a new instance of `ReplayResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplayResult().with { $0.diff = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case diff = "diff"
    case error = "error"
    case name = "name"
    case parent = "parent"
    case accessTuple = "accessTuple"
    case lastSeenDate = "lastSeenDate"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.accessTuple = try container.decodeIfPresent(AccessTuple.self, forKey: .accessTuple)
    self.lastSeenDate = try container.decodeIfPresent(GoogleType.Date.self, forKey: .lastSeenDate)

    var result: OneOf_Result? = nil
    let resultCheckAndSet = {
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = $0
    }
    if let diff = try container.decodeIfPresent(ReplayDiff?.self, forKey: .diff) {
      try resultCheckAndSet(.diff(diff))
    }
    if let error = try container.decodeIfPresent(GoogleRpc.Status?.self, forKey: .error) {
      try resultCheckAndSet(.error(error))
    }
    self.result = result
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.accessTuple, forKey: .accessTuple)
    try container.encode(self.lastSeenDate, forKey: .lastSeenDate)

    if let choice = self.result {
      switch choice {
      case .diff(let value):
        try container.encode(value, forKey: .diff)
      case .error(let value):
        try container.encode(value, forKey: .error)
      }
    }
  }

  /// The result of replaying the access tuple.
  public enum OneOf_Result: Codable, Equatable, Sendable {
    /// The difference between the principal's access under the current
    /// (baseline) policies and the principal's access under the proposed
    /// (simulated) policies.
    ///
    /// This field is only included for access tuples that were successfully
    /// replayed and had different results under the current policies and the
    /// proposed policies.
    indirect case diff(ReplayDiff?)
    /// The error that caused the access tuple replay to fail.
    ///
    /// This field is only included for access tuples that were not replayed
    /// successfully.
    indirect case error(GoogleRpc.Status?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.policysimulator.v1.ReplayResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
