// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Policy Simulator API service.
///
/// Policy Simulator is a collection of endpoints for creating, running, and
/// viewing a [Replay][google.cloud.policysimulator.v1.Replay]. A
/// [Replay][google.cloud.policysimulator.v1.Replay] is a type of simulation that
/// lets you see how your principals' access to resources might change if you
/// changed your IAM policy.
///
/// During a [Replay][google.cloud.policysimulator.v1.Replay], Policy Simulator
/// re-evaluates, or replays, past access attempts under both the current policy
/// and  your proposed policy, and compares those results to determine how your
/// principals' access might change under the proposed policy.
///
/// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
///
/// @Snippet(path: "SimulatorQuickstart")
public final class SimulatorClient: Clients.SimulatorProtocol, Sendable {
  let inner: any Clients.SimulatorStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `SimulatorClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.SimulatorStub = try Clients.SimulatorTransport(options)
    inner = Clients.SimulatorRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.SimulatorLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Gets the specified [Replay][google.cloud.policysimulator.v1.Replay]. Each
  /// `Replay` is available for at least 7 days.
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  ///
  /// @Snippet(path: "Simulator_GetReplay")
  public func getReplay(
    request: GetReplayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.Replay {
    try await self.inner.getReplay(request: request, options: options)
  }

  /// Creates and starts a [Replay][google.cloud.policysimulator.v1.Replay] using
  /// the given [ReplayConfig][google.cloud.policysimulator.v1.ReplayConfig].
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  /// [google.cloud.policysimulator.v1.ReplayConfig]: <doc:ReplayConfig>
  ///
  /// @Snippet(path: "Simulator_CreateReplay")
  public func createReplay(
    request: CreateReplayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createReplay(request: request, options: options)
  }

  /// Creates and starts a [Replay][google.cloud.policysimulator.v1.Replay] using
  /// the given [ReplayConfig][google.cloud.policysimulator.v1.ReplayConfig].
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  /// [google.cloud.policysimulator.v1.ReplayConfig]: <doc:ReplayConfig>
  ///
  /// @Snippet(path: "Simulator_CreateReplay")
  public func createReplayPollingUntilDone(
    request: CreateReplayRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Replay> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Replay>.State in
      return try op._extractStatus(Replay.self)
    }
    let rawOp = try await self.createReplay(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Replay>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the results of running a
  /// [Replay][google.cloud.policysimulator.v1.Replay].
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  ///
  /// @Snippet(path: "Simulator_ListReplayResults")
  public func listReplayResults(
    request: ListReplayResultsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse {
    try await self.inner.listReplayResults(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Simulator_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Simulator_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `SimulatorClient`.
  ///
  /// To mock `SimulatorClient` change your functions to receive
  /// `some SimulatorProtocol` or `any SimulatorProtocol`
  /// and pass a mock implementation in your tests.
  public protocol SimulatorProtocol: Sendable {
    /// See `SimulatorClient.getReplay`.
    func getReplay(
      request: GetReplayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.Replay

    /// See `SimulatorClient.createReplay`.
    func createReplay(
      request: CreateReplayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SimulatorClient.createReplay`.
    func createReplayPollingUntilDone(
      request: CreateReplayRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Replay>

    /// See `SimulatorClient.listReplayResults`.
    func listReplayResults(
      request: ListReplayResultsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse

    /// See `SimulatorClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse
  }
}

// Default implementations
extension Clients.SimulatorProtocol {
  public func getReplay(request: GetReplayRequest) async throws
    -> GoogleCloudPolicySimulatorV1.Replay
  {
    try await self.getReplay(request: request, options: .init())
  }

  public func getReplay(
    request: GetReplayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.Replay {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getReplay(
    name: Swift.String,
  ) async throws -> GoogleCloudPolicySimulatorV1.Replay {
    let request = GetReplayRequest().with {
      $0.name = name
    }
    return try await self.getReplay(request: request)
  }

  public func createReplay(request: CreateReplayRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createReplay(request: request, options: .init())
  }

  public func createReplay(
    request: CreateReplayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createReplayPollingUntilDone(request: CreateReplayRequest) async throws
    -> any GoogleGax.PollableOperation<Replay>
  {
    try await self.createReplayPollingUntilDone(request: request, options: .init())
  }

  public func createReplayPollingUntilDone(
    request: CreateReplayRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Replay> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Replay>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createReplayPollingUntilDone(
    parent: Swift.String,
    replay: Replay?,
  ) async throws -> any GoogleGax.PollableOperation<Replay> {
    let request = CreateReplayRequest().with {
      $0.parent = parent
      $0.replay = replay
    }
    return try await self.createReplayPollingUntilDone(request: request)
  }

  public func listReplayResults(request: ListReplayResultsRequest) async throws
    -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse
  {
    try await self.listReplayResults(request: request, options: .init())
  }

  public func listReplayResults(
    request: ListReplayResultsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listReplayResultsByItems(
    request: ListReplayResultsRequest
  ) -> some AsyncSequence<ReplayResult, Swift.Error> & Sendable {
    self.listReplayResultsByItems(request: request, options: .init())
  }

  /// Lists the results of running a
  /// [Replay][google.cloud.policysimulator.v1.Replay].
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  ///
  /// @Snippet(path: "Simulator_ListReplayResults")
  public func listReplayResultsByItems(
    request: ListReplayResultsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ReplayResult, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse in
      var request = request
      request.pageToken = token
      return try await self.listReplayResults(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReplayResultsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ReplayResult, Swift.Error> & Sendable {
    let request = ListReplayResultsRequest().with {
      $0.parent = parent
    }
    return self.listReplayResultsByItems(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Simulator_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
