// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Policy Simulator API service.
///
/// Policy Simulator is a collection of endpoints for creating, running, and
/// viewing a [Replay][google.cloud.policysimulator.v1.Replay]. A
/// [Replay][google.cloud.policysimulator.v1.Replay] is a type of simulation that
/// lets you see how your principals' access to resources might change if you
/// changed your IAM policy.
///
/// During a [Replay][google.cloud.policysimulator.v1.Replay], Policy Simulator
/// re-evaluates, or replays, past access attempts under both the current policy
/// and  your proposed policy, and compares those results to determine how your
/// principals' access might change under the proposed policy.
///
/// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
///
/// @Snippet(path: "SimulatorQuickstart")
public class SimulatorClient: Clients.SimulatorProtocol {
  let inner: any Clients.SimulatorStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `SimulatorClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.SimulatorStub = try Clients.SimulatorTransport(options)
    inner = Clients.SimulatorRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.SimulatorLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Gets the specified [Replay][google.cloud.policysimulator.v1.Replay]. Each
  /// `Replay` is available for at least 7 days.
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  ///
  /// @Snippet(path: "Simulator_GetReplay")
  public func getReplay(
    request: GetReplayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.Replay {
    try await self.inner.getReplay(request: request, options: options)
  }

  /// Creates and starts a [Replay][google.cloud.policysimulator.v1.Replay] using
  /// the given [ReplayConfig][google.cloud.policysimulator.v1.ReplayConfig].
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  /// [google.cloud.policysimulator.v1.ReplayConfig]: <doc:ReplayConfig>
  ///
  /// @Snippet(path: "Simulator_CreateReplay")
  public func createReplay(
    request: CreateReplayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createReplay(request: request, options: options)
  }

  /// Creates and starts a [Replay][google.cloud.policysimulator.v1.Replay] using
  /// the given [ReplayConfig][google.cloud.policysimulator.v1.ReplayConfig].
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  /// [google.cloud.policysimulator.v1.ReplayConfig]: <doc:ReplayConfig>
  ///
  /// @Snippet(path: "Simulator_CreateReplay")
  public func createReplay(
    withPolling: CreateReplayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Replay> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Replay>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Replay(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createReplay(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Replay>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists the results of running a
  /// [Replay][google.cloud.policysimulator.v1.Replay].
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  ///
  /// @Snippet(path: "Simulator_ListReplayResults")
  public func listReplayResults(
    request: ListReplayResultsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse {
    try await self.inner.listReplayResults(request: request, options: options)
  }

  /// Lists the results of running a
  /// [Replay][google.cloud.policysimulator.v1.Replay].
  ///
  /// [google.cloud.policysimulator.v1.Replay]: <doc:Replay>
  ///
  /// @Snippet(path: "Simulator_ListReplayResults")
  public func listReplayResults(
    byItem: ListReplayResultsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReplayResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listReplayResults(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Simulator_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Simulator_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "Simulator_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `SimulatorClient`.
  ///
  /// To mock `SimulatorClient` change your functions to receive
  /// `some SimulatorProtocol` or `any SimulatorProtocol`
  /// and pass a mock implementation in your tests.
  public protocol SimulatorProtocol {
    /// See `SimulatorClient.getReplay`.
    func getReplay(request: GetReplayRequest) async throws -> GoogleCloudPolicySimulatorV1.Replay

    /// See `SimulatorClient.getReplay`.
    func getReplay(
      name: Swift.String,
    ) async throws -> GoogleCloudPolicySimulatorV1.Replay

    /// See `SimulatorClient.createReplay`.
    func createReplay(request: CreateReplayRequest) async throws -> GoogleLongRunning.Operation

    /// See `SimulatorClient.createReplay`.
    func createReplay(withPolling: CreateReplayRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Replay>

    /// See `SimulatorClient.createReplay`.
    func createReplay(
      parent: Swift.String,
      replay: Replay?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Replay>

    /// See `SimulatorClient.listReplayResults`.
    func listReplayResults(request: ListReplayResultsRequest) async throws
      -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse

    /// See `SimulatorClient.listReplayResults`.
    func listReplayResults(
      byItem: ListReplayResultsRequest
    ) throws -> any AsyncSequence<ReplayResult, Swift.Error>

    /// See `SimulatorClient.listReplayResults`.
    func listReplayResults(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ReplayResult, Swift.Error>

    /// See `SimulatorClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `SimulatorClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `SimulatorClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `SimulatorClient.getReplay`.
    func getReplay(
      request: GetReplayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.Replay

    /// See `SimulatorClient.createReplay`.
    func createReplay(
      request: CreateReplayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `SimulatorClient.createReplay`.
    func createReplay(
      withPolling: CreateReplayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Replay>

    /// See `SimulatorClient.listReplayResults`.
    func listReplayResults(
      request: ListReplayResultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse

    /// See `SimulatorClient.listReplayResults`.
    func listReplayResults(
      byItem: ListReplayResultsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ReplayResult, Swift.Error>

    /// See `SimulatorClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `SimulatorClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>
  }
}

// Default implementations
extension Clients.SimulatorProtocol {
  public func getReplay(request: GetReplayRequest) async throws
    -> GoogleCloudPolicySimulatorV1.Replay
  {
    try await self.getReplay(request: request, options: .init())
  }

  public func getReplay(
    request: GetReplayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.Replay {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getReplay(
    name: Swift.String,
  ) async throws -> GoogleCloudPolicySimulatorV1.Replay {
    let request = GetReplayRequest().with {
      $0.name = name
    }
    return try await self.getReplay(request: request)
  }

  public func createReplay(request: CreateReplayRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createReplay(request: request, options: .init())
  }

  public func createReplay(
    request: CreateReplayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createReplay(withPolling: CreateReplayRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Replay>
  {
    try await self.createReplay(withPolling: withPolling, options: .init())
  }

  public func createReplay(
    withPolling: CreateReplayRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Replay> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Replay>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createReplay(
    parent: Swift.String,
    replay: Replay?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Replay> {
    let request = CreateReplayRequest().with {
      $0.parent = parent
      $0.replay = replay
    }
    return try await self.createReplay(withPolling: request)
  }

  public func listReplayResults(request: ListReplayResultsRequest) async throws
    -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse
  {
    try await self.listReplayResults(request: request, options: .init())
  }

  public func listReplayResults(
    request: ListReplayResultsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listReplayResults(
    byItem: ListReplayResultsRequest
  ) throws -> any AsyncSequence<ReplayResult, Swift.Error> {
    try self.listReplayResults(byItem: byItem, options: .init())
  }

  public func listReplayResults(
    byItem: ListReplayResultsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ReplayResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listReplayResults(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ReplayResult, Swift.Error> {
    let request = ListReplayResultsRequest().with {
      $0.parent = parent
    }
    return try self.listReplayResults(byItem: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
