// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class SimulatorLogging: SimulatorStub {
    let inner: any SimulatorStub
    let logger: Logger

    public init(_ inner: any SimulatorStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-policysimulator-v1"
      logger[metadataKey: "gcp.client.service"] = "policysimulator"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Simulator"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func getReplay(
      request: GetReplayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.Replay {
      try await self._intercept(
        request: request,
        options: options,
        name: "getReplay",
        action: {
          (r: GetReplayRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPolicySimulatorV1.Replay
          in
          return try await self.inner.getReplay(request: r, options: o)
        })
    }

    public func createReplay(
      request: CreateReplayRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createReplay",
        action: {
          (r: CreateReplayRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createReplay(request: r, options: o)
        })
    }

    public func listReplayResults(
      request: ListReplayResultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listReplayResults",
        action: {
          (r: ListReplayResultsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudPolicySimulatorV1.ListReplayResultsResponse
          in
          return try await self.inner.listReplayResults(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
